# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duedate', models.DateField(default=datetime.date.today)),
                ('priority', models.CharField(choices=[(b'h', b'high'), (b'm', b'medium'), (b'l', b'low')], default=b'l', max_length=1)),
                ('status', models.CharField(choices=[(b'g', b'green'), (b'y', b'yellow'), (b'r', b'red')], default=b'g', max_length=1)),
                ('comment', models.TextField(blank=True)),
                ('subtasks', models.ManyToManyField(blank=True, to='main.Task')),
            ],
        ),
    ]
